#ifndef HEADFIRST_DESIGNPATTERNS_01_STRATEGY_STRATEGICDUCK_FLYBEHAVIOR_H_
#define HEADFIRST_DESIGNPATTERNS_01_STRATEGY_STRATEGICDUCK_FLYBEHAVIOR_H_

class FlyBehavior {
 public:
  FlyBehavior(){};
  virtual ~FlyBehavior(){};

  virtual unsigned int fly() = 0;
};

#endif  // HEADFIRST_DESIGNPATTERNS_01_STRATEGY_STRATEGICDUCK_FLYBEHAVIOR_H_