#ifndef HEADFIRST_DESIGNPATTERNS_01_STRATEGY_STRATEGICDUCK_FLYWITHWINGS_H_
#define HEADFIRST_DESIGNPATTERNS_01_STRATEGY_STRATEGICDUCK_FLYWITHWINGS_H_

#include "FlyBehavior.h"

class FlyWithWings : public FlyBehavior {
 public:
  FlyWithWings();
  ~FlyWithWings();

  unsigned int fly();
};

#endif  // HEADFIRST_DESIGNPATTERNS_01_STRATEGY_STRATEGICDUCK_FLYWITHWINGS_H_
