#ifndef HEADFIRST_DESIGNPATTERNS_01_STRATEGY_STRATEGICDUCK_GLOBALINCLUDES_H_
#define HEADFIRST_DESIGNPATTERNS_01_STRATEGY_STRATEGICDUCK_GLOBALINCLUDES_H_

#include <iostream>

using std::cout;
using std::endl;

#endif  // HEADFIRST_DESIGNPATTERNS_01_STRATEGY_STRATEGICDUCK_GLOBALINCLUDES_H_