#ifndef HEADFIRST_DESIGNPATTERNS_01_STRATEGY_STRATEGICDUCK_QUACKBEHAVIOR_H_
#define HEADFIRST_DESIGNPATTERNS_01_STRATEGY_STRATEGICDUCK_QUACKBEHAVIOR_H_

class QuackBehavior {
 public:
  virtual ~QuackBehavior(){};

  virtual unsigned int quack() = 0;
};

#endif  // HEADFIRST_DESIGNPATTERNS_01_STRATEGY_STRATEGICDUCK_QUACKBEHAVIOR_H_